import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Rubik } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from './theme'

//export const dynamic = 'force-dynamic'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
    title: 'Sumscribe',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <AppRouterCacheProvider> {/*Required for MaterialUI*/}
                    <ThemeProvider theme={theme}>
                        {children}
                    </ThemeProvider>  
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
